version: '3'

services:
  backend-srpu-local:
    build: .
    environment:
      SRPU_B_APP_DB_HOST: "10.200.4.161"
      SRPU_B_APP_DB_USER: "root"
      SRPU_B_APP_DB_DATABASE: "SRPU"
      SRPU_B_APP_DB_PASSWORD: "xQRA0xBC87Gs"
      SRPU_B_APP_PORT: "3500"
      SRPU_B_APP_JWT_SECRET_KEY: "2A95F5CCD11DE255FEE9451BDE433"
      SRPU_B_APP_TOKEN_HEADER_KEY: "authorization"
      SRPU_B_APP_REFRESH_TOKEN_KEY: "4ebd020883285d698c44ec50939c8567" 
      SRPU_B_APP_EMAIL_USER: "noreply.cecapmex@gmail.com"
      SRPU_B_APP_EMAIL_PASSWORD: "hpffapcifkvkfuey"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3500:3000
      - 9229:9229
    restart: always