version: '3'

services:
  backend-srpu:
    build: .
    environment:
      SRPU_B_APP_DB_HOST: "10.200.4.77"
      SRPU_B_APP_DB_USER: "root"
      SRPU_B_APP_DB_DATABASE: "SRPU"
      SRPU_B_APP_DB_PASSWORD: "Cg98Z6222"
      SRPU_B_APP_PORT: "3000"
      SRPU_B_APP_JWT_SECRET_KEY: "2A95F5CCD11DE255FEE9451BDE568"
      SRPU_B_APP_TOKEN_HEADER_KEY: "authorization"
      SRPU_B_APP_EMAIL_USER: "noreply.cecapmex@gmail.com"
      SRPU_B_APP_EMAIL_PASSWORD: "hpffapcifkvkfuey"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3500:3000
      - 3030:9229
    restart: always